"use client";
import { FormEvent,useMemo,useState } from "react";
import { useFinance } from "../context/FinanceContext";
import { euro } from "../lib/format";
import { inputClass,labelClass,primaryButtonClass } from "../components/FormFields";
export default function BudzetiPage(){const{budgets,setBudget,transactions,profile}=useFinance();const[category,setCategory]=useState("Hrana");const[sortOrder,setSortOrder]=useState<"desc"|"asc">("desc");const[limit,setLimit]=useState("");const spent=useMemo(()=>transactions.filter(t=>t.type==="expense").reduce<Record<string,number>>((a,t)=>{a[t.category]=(a[t.category]??0)+t.amount;return a},{}),[transactions]);function submit(e:FormEvent){e.preventDefault();const n=Number(limit);if(category.trim()&&n>0){setBudget(category.trim(),n);setLimit("")}}
return <div className="space-y-6"><header><h1 className="text-3xl font-bold text-gray-900">Budžeti</h1><p className="mt-1 text-gray-500">Postavi mjesečne limite i odmah vidi koliko si blizu granice.</p></header><section className="grid gap-6 lg:grid-cols-3"><form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-gray-100"><p className="text-sm font-bold">Postavi ili promijeni limit</p><div className="mt-5 space-y-4"><label className={labelClass}>Kategorija<input className={inputClass} value={category} onChange={e=>setCategory(e.target.value)}/></label><label className={labelClass}>Mjesečni limit ({profile.currency})<input className={inputClass} type="number" min="1" value={limit} onChange={e=>setLimit(e.target.value)}/></label><button className={`${primaryButtonClass} w-full`}>Spremi budžet</button></div></form><div className="lg:col-span-2 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-gray-100"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
  <p className="text-sm font-bold">Aktivni budžeti</p>
  <select value={sortOrder} onChange={e=>setSortOrder(e.target.value as "desc"|"asc")} className="rounded-xl border border-gray-200 bg-gray-50 px-3 py-2 text-sm outline-none">
    <option value="desc">Najveći → najmanji</option>
    <option value="asc">Najmanji → najveći</option>
  </select>
</div><div className="mt-5 space-y-5">{[...budgets].sort((a,b)=>sortOrder==="desc" ? (spent[b.category]??0)-(spent[a.category]??0) : (spent[a.category]??0)-(spent[b.category]??0)).map(b=>{const used=spent[b.category]??0;const pct=Math.round(used/b.limit*100);return <div key={b.category}><div className="flex items-end justify-between"><div><p className="text-sm font-semibold">{b.category}</p><p className="text-xs text-gray-500">{euro(used,profile.currency)} od {euro(b.limit,profile.currency)}</p></div><span className={`text-sm font-bold ${pct>=100?"text-rose-600":pct>=80?"text-amber-600":"text-purple-900"}`}>{pct}%</span></div><div className="mt-2 h-3 rounded-full bg-gray-100"><div className={`h-3 rounded-full ${pct>=100?"bg-rose-500":pct>=80?"bg-amber-500":"bg-purple-900"}`} style={{width:`${Math.min(100,pct)}%`}}/></div></div>})}</div></div></section></div>}
